import *as gun0 from "./assets/items/firearms/AK-47/export.js";
import *as gun1 from "./assets/items/firearms/AKM/export.js";
import *as gun2 from "./assets/items/firearms/AN-94/export.js";
import *as gun3 from "./assets/items/firearms/AWM-S/export.js";
import *as gun4 from "./assets/items/firearms/Dual M1911/export.js";
import *as gun5 from "./assets/items/firearms/Dual M9/export.js";
import *as gun6 from "./assets/items/firearms/Dual OTs-38/export.js";
import *as gun7 from "./assets/items/firearms/Dual P30L/export.js";
import *as gun8 from "./assets/items/firearms/FAMAS/export.js";
import *as gun9 from "./assets/items/firearms/L86A2/export.js";
import *as gun10 from "./assets/items/firearms/M134/export.js";
import *as gun11 from "./assets/items/firearms/M1911/export.js";
import *as gun12 from "./assets/items/firearms/M4A1-S/export.js";
import *as gun13 from "./assets/items/firearms/M79/export.js";
import *as gun14 from "./assets/items/firearms/M870/export.js";
import *as gun15 from "./assets/items/firearms/M9/export.js";
import *as gun16 from "./assets/items/firearms/MP220/export.js";
import *as gun17 from "./assets/items/firearms/Mosin-Nagant/export.js";
import *as gun18 from "./assets/items/firearms/OTs-38/export.js";
import *as gun19 from "./assets/items/firearms/P30L/export.js";
import *as gun20 from "./assets/items/firearms/PKP Pecheneg/export.js";
import *as gun21 from "./assets/items/firearms/SV-98/export.js";
import *as gun22 from "./assets/items/firearms/USAS-12/export.js";
parseGunData([gun0.default, gun1.default, gun2.default, gun3.default, gun4.default, gun5.default, gun6.default, gun7.default, gun8.default, gun9.default, gun10.default, gun11.default, gun12.default, gun13.default, gun14.default, gun15.default, gun16.default, gun17.default, gun18.default, gun19.default, gun20.default, gun21.default, gun22.default]).forEach(e => gamespace.guns.set(e.name, e));
gamespace.events.dispatchEvent("gunsLoaded");
import *as ammo0 from "./assets/items/ammo/12 gauge/export.js";
import *as ammo1 from "./assets/items/ammo/308sub/export.js";
import *as ammo2 from "./assets/items/ammo/40mm/export.js";
import *as ammo3 from "./assets/items/ammo/45ACP/export.js";
import *as ammo4 from "./assets/items/ammo/556mm/export.js";
import *as ammo5 from "./assets/items/ammo/762mm/export.js";
import *as ammo6 from "./assets/items/ammo/9mm/export.js";
parseAmmoData([ammo0.default, ammo1.default, ammo2.default, ammo3.default, ammo4.default, ammo5.default, ammo6.default]).forEach(e => gamespace.bulletInfo.set(e.name, e));
gamespace.events.dispatchEvent("ammosLoaded");
import *as explosion0 from "./assets/explosions/frag/export.js";
import *as explosion1 from "./assets/explosions/usas/export.js";
parseExplosionData([explosion0.default, explosion1.default]).forEach(e => gamespace.explosionInfo.set(e.name, e));
gamespace.events.dispatchEvent("explosionsLoaded");
import { level as level0 } from "./assets/levels/level0/level.js";
import { level as level1 } from "./assets/levels/level1/level.js";
import { level as level2 } from "./assets/levels/level2/level.js";
[level0, level1, level2].forEach(l => gamespace.levels.set(l.name, l));
gamespace.events.dispatchEvent("levelsLoaded");