import*as ammo0 from"./assets/default/ammos/12 gauge (birdshot)/export.js"
import*as ammo1 from"./assets/default/ammos/12 gauge (buckshot)/export.js"
import*as ammo2 from"./assets/default/ammos/12 gauge (flechette)/export.js"
import*as ammo3 from"./assets/default/ammos/12 gauge (slug)/export.js"
import*as ammo4 from"./assets/default/ammos/30-06/export.js"
import*as ammo5 from"./assets/default/ammos/308sub/export.js"
import*as ammo6 from"./assets/default/ammos/40mm/export.js"
import*as ammo7 from"./assets/default/ammos/45ACP/export.js"
import*as ammo8 from"./assets/default/ammos/50AE/export.js"
import*as ammo9 from"./assets/default/ammos/556x45mm/export.js"
import*as ammo10 from"./assets/default/ammos/762x39mm/export.js"
import*as ammo11 from"./assets/default/ammos/762x41mm/export.js"
import*as ammo12 from"./assets/default/ammos/762x51mm/export.js"
import*as ammo13 from"./assets/default/ammos/762x54mmR/export.js"
import*as ammo14 from"./assets/default/ammos/9x19mm/export.js"
import*as ammo15 from"./assets/default/ammos/9x19mm cursed/export.js"
import*as ammo16 from"./assets/default/ammos/9x39mm/export.js"
import*as ammo17 from"./assets/default/ammos/FRAG-12/export.js"
import*as ammo18 from"./assets/default/ammos/Fire Shot/export.js"
import*as ammo19 from"./assets/default/ammos/Heart Explosive/export.js"
import*as ammo20 from"./assets/default/ammos/Lasr ammo/export.js"
import*as ammo21 from"./assets/default/ammos/Potato Explosive/export.js"
import*as ammo22 from"./assets/default/ammos/Potato Spud/export.js"
import*as ammo23 from"./assets/default/ammos/Rainbow Ammo/export.js"
import*as ammo24 from"./assets/default/ammos/Water/export.js"
import*as decal0 from"./assets/default/decals/decal_frag_explosion/export.js"
import*as decal1 from"./assets/default/decals/decal_frag_small_explosion/export.js"
import*as decal2 from"./assets/default/decals/decal_heart_explosion/export.js"
import*as decal3 from"./assets/default/decals/decal_rounds_explosion/export.js"
import*as decal4 from"./assets/default/decals/decal_snownball_explosion/export.js"
import*as decal5 from"./assets/default/decals/map-barrel-res/export.js"
import*as explosion0 from"./assets/default/explosions/explosion_fire/export.js"
import*as explosion1 from"./assets/default/explosions/explosion_frag/export.js"
import*as explosion2 from"./assets/default/explosions/explosion_heart_cannon/export.js"
import*as explosion3 from"./assets/default/explosions/explosion_potato_cannon/export.js"
import*as explosion4 from"./assets/default/explosions/explosion_potato_smg/export.js"
import*as explosion5 from"./assets/default/explosions/explosion_rainbow_blaster/export.js"
import*as explosion6 from"./assets/default/explosions/explosion_usas/export.js"
import*as explosion7 from"./assets/default/explosions/explosion_water/export.js"
import*as firearm0 from"./assets/default/firearms/AK-47/export.js"
import*as firearm1 from"./assets/default/firearms/AN-94/export.js"
import*as firearm2 from"./assets/default/firearms/AWM-S/export.js"
import*as firearm3 from"./assets/default/firearms/BAR M1918/export.js"
import*as firearm4 from"./assets/default/firearms/BLR 81/export.js"
import*as firearm5 from"./assets/default/firearms/CZ-3A1/export.js"
import*as firearm6 from"./assets/default/firearms/DEagle 50/export.js"
import*as firearm7 from"./assets/default/firearms/DP-28/export.js"
import*as firearm8 from"./assets/default/firearms/Dual DEagle 50/export.js"
import*as firearm9 from"./assets/default/firearms/Dual G18C/export.js"
import*as firearm10 from"./assets/default/firearms/Dual Lasr Gun/export.js"
import*as firearm11 from"./assets/default/firearms/Dual M1911/export.js"
import*as firearm12 from"./assets/default/firearms/Dual M9/export.js"
import*as firearm13 from"./assets/default/firearms/Dual M93R/export.js"
import*as firearm14 from"./assets/default/firearms/Dual OT-38/export.js"
import*as firearm15 from"./assets/default/firearms/Dual OTs-38/export.js"
import*as firearm16 from"./assets/default/firearms/Dual P30L/export.js"
import*as firearm17 from"./assets/default/firearms/Dual Peacemaker/export.js"
import*as firearm18 from"./assets/default/firearms/FAMAS/export.js"
import*as firearm19 from"./assets/default/firearms/G18C/export.js"
import*as firearm20 from"./assets/default/firearms/Groza/export.js"
import*as firearm21 from"./assets/default/firearms/Groza-S/export.js"
import*as firearm22 from"./assets/default/firearms/Hawk 12G/export.js"
import*as firearm23 from"./assets/default/firearms/Heart Cannon/export.js"
import*as firearm24 from"./assets/default/firearms/L86A2/export.js"
import*as firearm25 from"./assets/default/firearms/Lasr Gun/export.js"
import*as firearm26 from"./assets/default/firearms/M1 Garand/export.js"
import*as firearm27 from"./assets/default/firearms/M1100/export.js"
import*as firearm28 from"./assets/default/firearms/M134/export.js"
import*as firearm29 from"./assets/default/firearms/M1911/export.js"
import*as firearm30 from"./assets/default/firearms/M1A1/export.js"
import*as firearm31 from"./assets/default/firearms/M249/export.js"
import*as firearm32 from"./assets/default/firearms/M39 EMR/export.js"
import*as firearm33 from"./assets/default/firearms/M416/export.js"
import*as firearm34 from"./assets/default/firearms/M4A1-S/export.js"
import*as firearm35 from"./assets/default/firearms/M79/export.js"
import*as firearm36 from"./assets/default/firearms/M870/export.js"
import*as firearm37 from"./assets/default/firearms/M9/export.js"
import*as firearm38 from"./assets/default/firearms/M9 Cursed/export.js"
import*as firearm39 from"./assets/default/firearms/M93R/export.js"
import*as firearm40 from"./assets/default/firearms/M9A17/export.js"
import*as firearm41 from"./assets/default/firearms/MAC-10/export.js"
import*as firearm42 from"./assets/default/firearms/MP220/export.js"
import*as firearm43 from"./assets/default/firearms/MP5/export.js"
import*as firearm44 from"./assets/default/firearms/Mk12 SPR/export.js"
import*as firearm45 from"./assets/default/firearms/Mk20 SSR/export.js"
import*as firearm46 from"./assets/default/firearms/Mk45G/export.js"
import*as firearm47 from"./assets/default/firearms/Model 94/export.js"
import*as firearm48 from"./assets/default/firearms/Mosin-Nagant/export.js"
import*as firearm49 from"./assets/default/firearms/OT-38/export.js"
import*as firearm50 from"./assets/default/firearms/OTs-38/export.js"
import*as firearm51 from"./assets/default/firearms/P30L/export.js"
import*as firearm52 from"./assets/default/firearms/PKM/export.js"
import*as firearm53 from"./assets/default/firearms/PKP Pecheneg/export.js"
import*as firearm54 from"./assets/default/firearms/Peacemaker/export.js"
import*as firearm55 from"./assets/default/firearms/Potato Cannon/export.js"
import*as firearm56 from"./assets/default/firearms/QBB-97/export.js"
import*as firearm57 from"./assets/default/firearms/Rainbow Blaster/export.js"
import*as firearm58 from"./assets/default/firearms/SCAR-H/export.js"
import*as firearm59 from"./assets/default/firearms/SPAS-12/export.js"
import*as firearm60 from"./assets/default/firearms/SV-98/export.js"
import*as firearm61 from"./assets/default/firearms/SVD-63/export.js"
import*as firearm62 from"./assets/default/firearms/Saiga-12/export.js"
import*as firearm63 from"./assets/default/firearms/Scout Elite/export.js"
import*as firearm64 from"./assets/default/firearms/Spud Gun/export.js"
import*as firearm65 from"./assets/default/firearms/Super 90/export.js"
import*as firearm66 from"./assets/default/firearms/UMP9/export.js"
import*as firearm67 from"./assets/default/firearms/USAS-12/export.js"
import*as firearm68 from"./assets/default/firearms/VSS/export.js"
import*as firearm69 from"./assets/default/firearms/Vector (.45ACP)/export.js"
import*as firearm70 from"./assets/default/firearms/Vector (9mm)/export.js"
import*as firearm71 from"./assets/default/firearms/Water Gun/export.js"
import*as firearm72 from"./assets/extras/firearms/Dual TBD/export.js"
import*as firearm73 from"./assets/extras/firearms/TBD/export.js"
import*as level0 from"./assets/default/levels/level0/export.js"
import*as particle0 from"./assets/default/particles/blood_splat/export.js"
import*as particle1 from"./assets/default/particles/casing_12gauge_birdshot/export.js"
import*as particle2 from"./assets/default/particles/casing_12gauge_buckshot/export.js"
import*as particle3 from"./assets/default/particles/casing_12gauge_flechette/export.js"
import*as particle4 from"./assets/default/particles/casing_12gauge_slug/export.js"
import*as particle5 from"./assets/default/particles/casing_30-06/export.js"
import*as particle6 from"./assets/default/particles/casing_308/export.js"
import*as particle7 from"./assets/default/particles/casing_40mm/export.js"
import*as particle8 from"./assets/default/particles/casing_45acp/export.js"
import*as particle9 from"./assets/default/particles/casing_50AE/export.js"
import*as particle10 from"./assets/default/particles/casing_556x45mm/export.js"
import*as particle11 from"./assets/default/particles/casing_762x39mm/export.js"
import*as particle12 from"./assets/default/particles/casing_762x41mm/export.js"
import*as particle13 from"./assets/default/particles/casing_762x51mm/export.js"
import*as particle14 from"./assets/default/particles/casing_762x54mmR/export.js"
import*as particle15 from"./assets/default/particles/casing_9x19mm/export.js"
import*as particle16 from"./assets/default/particles/casing_9x19mm_cursed/export.js"
import*as particle17 from"./assets/default/particles/casing_9x39mm/export.js"
import*as particle18 from"./assets/default/particles/casing_frag12/export.js"
import*as particle19 from"./assets/default/particles/casing_heart/export.js"
import*as particle20 from"./assets/default/particles/casing_potato/export.js"
import*as particle21 from"./assets/default/particles/casing_rainbow_ammo/export.js"
import*as particle22 from"./assets/default/particles/casing_water/export.js"
import*as particle23 from"./assets/default/particles/explosionBurst/export.js"
import*as particle24 from"./assets/default/particles/explosionHeart/export.js"
import*as particle25 from"./assets/default/particles/explosionPotato/export.js"
import*as particle26 from"./assets/default/particles/explosionRounds/export.js"
import*as particle27 from"./assets/default/particles/explosionUSAS/export.js"
import*as particle28 from"./assets/default/particles/fire_effect/export.js"
import*as particle29 from"./assets/default/particles/fire_impact/export.js"
import*as particle30 from"./assets/default/particles/frenemy/export.js"
import*as particle31 from"./assets/default/particles/heart_impact/export.js"
import*as particle32 from"./assets/default/particles/potato_impact/export.js"
import*as particle33 from"./assets/default/particles/potato_smg_impact/export.js"
import*as particle34 from"./assets/default/particles/rainbow_ball/export.js"
import*as particle35 from"./assets/default/particles/water_balloon_impact/export.js"
import*as particle36 from"./assets/default/particles/wet_effect/export.js"
import*as status_effect0 from"./assets/default/status_effects/burn/export.js"
import*as status_effect1 from"./assets/default/status_effects/frenemy/export.js"
import*as status_effect2 from"./assets/default/status_effects/potato-smg-hit/export.js"
import*as status_effect3 from"./assets/default/status_effects/wet/export.js"
import*as melee0 from"./assets/default/melees/bayonet_rugged/export.js"
import*as melee1 from"./assets/default/melees/bayonet_woodland/export.js"
import*as melee2 from"./assets/default/melees/bonesaw_healer/export.js"
import*as melee3 from"./assets/default/melees/bonesaw_rusted/export.js"
import*as melee4 from"./assets/default/melees/bowie_frontier/export.js"
import*as melee5 from"./assets/default/melees/bowie_vintage/export.js"
import*as melee6 from"./assets/default/melees/fireaxe/export.js"
import*as melee7 from"./assets/default/melees/fists/export.js"
import*as melee8 from"./assets/default/melees/hook/export.js"
import*as melee9 from"./assets/default/melees/huntsman_burnished/export.js"
import*as melee10 from"./assets/default/melees/huntsman_rugged/export.js"
import*as melee11 from"./assets/default/melees/karambit_drowned/export.js"
import*as melee12 from"./assets/default/melees/karambit_prismatic/export.js"
import*as melee13 from"./assets/default/melees/karambit_rugged/export.js"
import*as melee14 from"./assets/default/melees/katana/export.js"
import*as melee15 from"./assets/default/melees/katana_demo/export.js"
import*as melee16 from"./assets/default/melees/katana_orchid/export.js"
import*as melee17 from"./assets/default/melees/katana_rusted/export.js"
import*as melee18 from"./assets/default/melees/kukri_sniper/export.js"
import*as melee19 from"./assets/default/melees/kukri_trad/export.js"
import*as melee20 from"./assets/default/melees/machete_taiga/export.js"
import*as melee21 from"./assets/default/melees/naginata/export.js"
import*as melee22 from"./assets/default/melees/pan/export.js"
import*as melee23 from"./assets/default/melees/sledgehammer/export.js"
import*as melee24 from"./assets/default/melees/stonehammer/export.js"
import*as melee25 from"./assets/default/melees/woodaxe/export.js"
import*as melee26 from"./assets/default/melees/woodaxe_bloody/export.js"
{const s=Date.now();await Promise.allSettled([parseFunctions.parseAmmoData([{...ammo0.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/12 gauge (birdshot)"},{...ammo1.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/12 gauge (buckshot)"},{...ammo2.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/12 gauge (flechette)"},{...ammo3.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/12 gauge (slug)"},{...ammo4.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/30-06"},{...ammo5.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/308sub"},{...ammo6.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/40mm"},{...ammo7.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/45ACP"},{...ammo8.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/50AE"},{...ammo9.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/556x45mm"},{...ammo10.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/762x39mm"},{...ammo11.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/762x41mm"},{...ammo12.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/762x51mm"},{...ammo13.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/762x54mmR"},{...ammo14.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/9x19mm"},{...ammo15.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/9x19mm cursed"},{...ammo16.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/9x39mm"},{...ammo17.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/FRAG-12"},{...ammo18.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Fire Shot"},{...ammo19.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Heart Explosive"},{...ammo20.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Lasr ammo"},{...ammo21.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Potato Explosive"},{...ammo22.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Potato Spud"},{...ammo23.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Rainbow Ammo"},{...ammo24.default,namespace:"srvsdbx",includePath:"./assets/default/ammos/Water"}]),parseFunctions.parseDecalData([{...decal0.default,namespace:"srvsdbx",includePath:"./assets/default/decals/decal_frag_explosion"},{...decal1.default,namespace:"srvsdbx",includePath:"./assets/default/decals/decal_frag_small_explosion"},{...decal2.default,namespace:"srvsdbx",includePath:"./assets/default/decals/decal_heart_explosion"},{...decal3.default,namespace:"srvsdbx",includePath:"./assets/default/decals/decal_rounds_explosion"},{...decal4.default,namespace:"srvsdbx",includePath:"./assets/default/decals/decal_snownball_explosion"},{...decal5.default,namespace:"srvsdbx",includePath:"./assets/default/decals/map-barrel-res"}]),parseFunctions.parseExplosionData([{...explosion0.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_fire"},{...explosion1.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_frag"},{...explosion2.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_heart_cannon"},{...explosion3.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_potato_cannon"},{...explosion4.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_potato_smg"},{...explosion5.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_rainbow_blaster"},{...explosion6.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_usas"},{...explosion7.default,namespace:"srvsdbx",includePath:"./assets/default/explosions/explosion_water"}]),parseFunctions.parseGunData([{...firearm0.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/AK-47"},{...firearm1.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/AN-94"},{...firearm2.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/AWM-S"},{...firearm3.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/BAR M1918"},{...firearm4.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/BLR 81"},{...firearm5.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/CZ-3A1"},{...firearm6.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/DEagle 50"},{...firearm7.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/DP-28"},{...firearm8.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual DEagle 50"},{...firearm9.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual G18C"},{...firearm10.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual Lasr Gun"},{...firearm11.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual M1911"},{...firearm12.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual M9"},{...firearm13.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual M93R"},{...firearm14.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual OT-38"},{...firearm15.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual OTs-38"},{...firearm16.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual P30L"},{...firearm17.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Dual Peacemaker"},{...firearm18.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/FAMAS"},{...firearm19.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/G18C"},{...firearm20.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Groza"},{...firearm21.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Groza-S"},{...firearm22.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Hawk 12G"},{...firearm23.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Heart Cannon"},{...firearm24.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/L86A2"},{...firearm25.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Lasr Gun"},{...firearm26.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M1 Garand"},{...firearm27.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M1100"},{...firearm28.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M134"},{...firearm29.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M1911"},{...firearm30.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M1A1"},{...firearm31.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M249"},{...firearm32.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M39 EMR"},{...firearm33.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M416"},{...firearm34.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M4A1-S"},{...firearm35.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M79"},{...firearm36.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M870"},{...firearm37.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M9"},{...firearm38.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M9 Cursed"},{...firearm39.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M93R"},{...firearm40.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/M9A17"},{...firearm41.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/MAC-10"},{...firearm42.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/MP220"},{...firearm43.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/MP5"},{...firearm44.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Mk12 SPR"},{...firearm45.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Mk20 SSR"},{...firearm46.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Mk45G"},{...firearm47.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Model 94"},{...firearm48.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Mosin-Nagant"},{...firearm49.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/OT-38"},{...firearm50.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/OTs-38"},{...firearm51.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/P30L"},{...firearm52.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/PKM"},{...firearm53.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/PKP Pecheneg"},{...firearm54.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Peacemaker"},{...firearm55.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Potato Cannon"},{...firearm56.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/QBB-97"},{...firearm57.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Rainbow Blaster"},{...firearm58.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/SCAR-H"},{...firearm59.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/SPAS-12"},{...firearm60.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/SV-98"},{...firearm61.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/SVD-63"},{...firearm62.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Saiga-12"},{...firearm63.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Scout Elite"},{...firearm64.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Spud Gun"},{...firearm65.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Super 90"},{...firearm66.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/UMP9"},{...firearm67.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/USAS-12"},{...firearm68.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/VSS"},{...firearm69.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Vector (.45ACP)"},{...firearm70.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Vector (9mm)"},{...firearm71.default,namespace:"srvsdbx",includePath:"./assets/default/firearms/Water Gun"},{...firearm72.default,namespace:"extras",includePath:"./assets/extras/firearms/Dual TBD"},{...firearm73.default,namespace:"extras",includePath:"./assets/extras/firearms/TBD"}]),gamespace.levels.push(level0.default),parseFunctions.parseParticleData([{...particle0.default,namespace:"srvsdbx",includePath:"./assets/default/particles/blood_splat"},{...particle1.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_12gauge_birdshot"},{...particle2.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_12gauge_buckshot"},{...particle3.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_12gauge_flechette"},{...particle4.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_12gauge_slug"},{...particle5.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_30-06"},{...particle6.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_308"},{...particle7.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_40mm"},{...particle8.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_45acp"},{...particle9.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_50AE"},{...particle10.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_556x45mm"},{...particle11.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_762x39mm"},{...particle12.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_762x41mm"},{...particle13.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_762x51mm"},{...particle14.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_762x54mmR"},{...particle15.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_9x19mm"},{...particle16.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_9x19mm_cursed"},{...particle17.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_9x39mm"},{...particle18.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_frag12"},{...particle19.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_heart"},{...particle20.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_potato"},{...particle21.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_rainbow_ammo"},{...particle22.default,namespace:"srvsdbx",includePath:"./assets/default/particles/casing_water"},{...particle23.default,namespace:"srvsdbx",includePath:"./assets/default/particles/explosionBurst"},{...particle24.default,namespace:"srvsdbx",includePath:"./assets/default/particles/explosionHeart"},{...particle25.default,namespace:"srvsdbx",includePath:"./assets/default/particles/explosionPotato"},{...particle26.default,namespace:"srvsdbx",includePath:"./assets/default/particles/explosionRounds"},{...particle27.default,namespace:"srvsdbx",includePath:"./assets/default/particles/explosionUSAS"},{...particle28.default,namespace:"srvsdbx",includePath:"./assets/default/particles/fire_effect"},{...particle29.default,namespace:"srvsdbx",includePath:"./assets/default/particles/fire_impact"},{...particle30.default,namespace:"srvsdbx",includePath:"./assets/default/particles/frenemy"},{...particle31.default,namespace:"srvsdbx",includePath:"./assets/default/particles/heart_impact"},{...particle32.default,namespace:"srvsdbx",includePath:"./assets/default/particles/potato_impact"},{...particle33.default,namespace:"srvsdbx",includePath:"./assets/default/particles/potato_smg_impact"},{...particle34.default,namespace:"srvsdbx",includePath:"./assets/default/particles/rainbow_ball"},{...particle35.default,namespace:"srvsdbx",includePath:"./assets/default/particles/water_balloon_impact"},{...particle36.default,namespace:"srvsdbx",includePath:"./assets/default/particles/wet_effect"}]),parseFunctions.parseStatusEffectData([{...status_effect0.default,namespace:"srvsdbx",includePath:"./assets/default/status_effects/burn"},{...status_effect1.default,namespace:"srvsdbx",includePath:"./assets/default/status_effects/frenemy"},{...status_effect2.default,namespace:"srvsdbx",includePath:"./assets/default/status_effects/potato-smg-hit"},{...status_effect3.default,namespace:"srvsdbx",includePath:"./assets/default/status_effects/wet"}]),parseFunctions.parseMeleeData([{...melee0.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bayonet_rugged"},{...melee1.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bayonet_woodland"},{...melee2.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bonesaw_healer"},{...melee3.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bonesaw_rusted"},{...melee4.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bowie_frontier"},{...melee5.default,namespace:"srvsdbx",includePath:"./assets/default/melees/bowie_vintage"},{...melee6.default,namespace:"srvsdbx",includePath:"./assets/default/melees/fireaxe"},{...melee7.default,namespace:"srvsdbx",includePath:"./assets/default/melees/fists"},{...melee8.default,namespace:"srvsdbx",includePath:"./assets/default/melees/hook"},{...melee9.default,namespace:"srvsdbx",includePath:"./assets/default/melees/huntsman_burnished"},{...melee10.default,namespace:"srvsdbx",includePath:"./assets/default/melees/huntsman_rugged"},{...melee11.default,namespace:"srvsdbx",includePath:"./assets/default/melees/karambit_drowned"},{...melee12.default,namespace:"srvsdbx",includePath:"./assets/default/melees/karambit_prismatic"},{...melee13.default,namespace:"srvsdbx",includePath:"./assets/default/melees/karambit_rugged"},{...melee14.default,namespace:"srvsdbx",includePath:"./assets/default/melees/katana"},{...melee15.default,namespace:"srvsdbx",includePath:"./assets/default/melees/katana_demo"},{...melee16.default,namespace:"srvsdbx",includePath:"./assets/default/melees/katana_orchid"},{...melee17.default,namespace:"srvsdbx",includePath:"./assets/default/melees/katana_rusted"},{...melee18.default,namespace:"srvsdbx",includePath:"./assets/default/melees/kukri_sniper"},{...melee19.default,namespace:"srvsdbx",includePath:"./assets/default/melees/kukri_trad"},{...melee20.default,namespace:"srvsdbx",includePath:"./assets/default/melees/machete_taiga"},{...melee21.default,namespace:"srvsdbx",includePath:"./assets/default/melees/naginata"},{...melee22.default,namespace:"srvsdbx",includePath:"./assets/default/melees/pan"},{...melee23.default,namespace:"srvsdbx",includePath:"./assets/default/melees/sledgehammer"},{...melee24.default,namespace:"srvsdbx",includePath:"./assets/default/melees/stonehammer"},{...melee25.default,namespace:"srvsdbx",includePath:"./assets/default/melees/woodaxe"},{...melee26.default,namespace:"srvsdbx",includePath:"./assets/default/melees/woodaxe_bloody"}])]);gamespace.events.dispatchEvent("ready",Date.now()-s)}